### ISSUE TITLE
Query on async endpoint failing where sync endpoint succeeds

### ISSUE THREAD

**Issue by andrewsu** [NCATSTranslator/minihackathons#363]
When I run the query pasted below on my local instance using the sync endpoint, I get a file with 7293 results, 691 nodes, 9927 edges.  The query completes in ~18 minutes.  The timing and the result/node/edge counts are consistent -- exact same results 3 times over 2 days.  However, when I run the query via my local asyncquery endpoint, the query fails.  This is the tail end of the console output:

```
  bte:biothings-explorer-trapi:UpdatedExeEdge (7) Collecting Types: "["ProteinIsoform","Protein","Gene"]" +0ms
  bte:biothings-explorer-trapi:UpdatedExeEdge Collected entity ids in results: ["Gene","Protein"] +346ms
  bte:biothings-explorer-trapi:NewQNode Node "n1" intersecting (179)/(714) curies... +347ms
  bte:biothings-explorer-trapi:NewQNode Node "n1" kept (172) curies... +235ms
  bte:biothings-explorer-trapi:main (10) Edge successfully queried. +14m
  bte:biothings-explorer-trapi:edge-manager (11) Collecting results... +2s
  bte:biothings-explorer-trapi:edge-manager (11) 'e0' keeps (487) results! +0ms
  bte:biothings-explorer-trapi:edge-manager ---------- +0ms
  bte:biothings-explorer-trapi:edge-manager (11) 'e1' keeps (12467) results! +0ms
  bte:biothings-explorer-trapi:edge-manager ---------- +0ms
  bte:biothings-explorer-trapi:edge-manager (11) 'e2' keeps (1091) results! +0ms
  bte:biothings-explorer-trapi:edge-manager ---------- +0ms
  bte:biothings-explorer-trapi:edge-manager (12) Collected results for: ["e0","e1","e2"]! +0ms
  bte:biothings-explorer-trapi:edge-manager (12) Collected (14045) results! +0ms
  bte:biothings-explorer-trapi:edge-manager (13) Edge Manager reporting combined results... +0ms
  bte:biothings-explorer-trapi:Graph Updating BTE Graph now. +0ms
  bte:biothings-explorer-trapi:edge-manager (13) Edge Manager reporting organized results... +209ms
  bte:biothings-explorer-trapi:QueryResult Updating query results now! +0ms
  bte:biothings-explorer-trapi:main (14) TRAPI query finished. +55s
err Error: Missing lock for job JG0R89wD7r failed
    at Object.finishedErrors (/home/asu/Science/bte-trapi-workspace/node_modules/bull/lib/scripts.js:189:16)
    at Job.moveToFailed (/home/asu/Science/bte-trapi-workspace/node_modules/bull/lib/job.js:342:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Query (should be the same as [Query D.6](https://github.com/NCATSTranslator/minihackathons/blob/main/2021-12_demo/workflowD/D.6_metformin-ferritin.json)): 
```
{
  "message": {
    "query_graph": {
      "nodes": {
        "n0": {
          "ids": ["CHEMBL.COMPOUND:CHEMBL1431"],
          "categories": ["biolink:SmallMolecule"]
        },
        "n1": {
          "categories": ["biolink:Protein"]
        },
        "n2": {
          "categories": ["biolink:Protein"]
        },
        "n3": {
          "ids": ["UniProtKB:P02794", "UniProtKB:P02792"],
          "categories": ["biolink:Protein"]
        }
      },
      "edges": {
        "e0": {
          "subject": "n0",
          "object": "n1"
        },
        "e1": {
          "subject": "n1",
          "object": "n2"
        },
        "e2": {
          "subject": "n2",
          "object": "n3"
        }
      }
    }
  }
}
```

NOTE: My local environment has the main branch of all repos, *except* for commenting out the text mining provider from the config.  (Incidentally I did run it once with text mining provider included, and it actually returned successfully in 3.5 hours with a 150 MB file, 52250 results.)  

```
$ git diff config.js
diff --git a/src/routes/v1/config.js b/src/routes/v1/config.js
index a46a8d7..3b16e62 100644
--- a/src/routes/v1/config.js
+++ b/src/routes/v1/config.js
@@ -98,10 +98,10 @@ exports.API_LIST = [
     },
     // Text Mining Provider collab, annotated with x-bte
     // - removed Text Mining Co-occurrence API since there were issues using it with BTE (too many answers)
-    {
-        id: '978fe380a147a8641caf72320862697b',
-        name: 'Text Mining Targeted Association API'
-    },
+ //   {
+//        id: '978fe380a147a8641caf72320862697b',
+//        name: 'Text Mining Targeted Association API'
+//    },
     // Automat APIs, ingested through TRAPI
     {
     // this API overlaps with our Biolink API registration, but we have bugs with our ingest...
```

May be relevant to slack thread here: https://suwulab.slack.com/archives/CC218TEKC/p1637610694124100

**Comment by andrewsu** [comment]
argh opened this issue on the wrong repo... 🤦‍♂️
